name: Daily Interview Reminder

on:
  schedule:
    # Runs every day at 8:00 AM IST (which is 2:30 AM UTC)
    - cron: "30 2 * * *"
  workflow_dispatch:  # allows manual trigger from the GitHub Actions tab

jobs:
  run-daily-reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run daily interview reminder script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}
        run: |
          python scripts/daily_interview_reminder
